### ISSUE TITLE
JOSS: Add  Issue templates 

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#10]
- If this repo will be used by "biomechanics researchers and clinicians with a limited mathematical background", we'll need to guide them properly
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
Addressed in ae753f020cfc80696ee74e28224fb259153975ef.
