### ISSUE TITLE
JOSS: Add Pull request template 

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#11]
- If this repo will be used by "biomechanics researchers and clinicians with a limited mathematical background", we'll need to guide them properly
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
Done in https://github.com/klevis-a/kinematics-vis/commit/935619b12d7e1126cfe8b78d4bea73bd164d2d76.
