### ISSUE TITLE
JOSS: Add versioning

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#13]
- Versioning is especially important in research, where exact versions of software/tools should always be cited
- This repo currently has no releases or versioning
- SemVer or CalVer are recommended
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
Released version 0.1.0 of software.

**Comment by engnadeau** [comment]
- closing issue
- fyi any further changes to the codebase for JOSS could potentially bump the version

**Comment by klevis-a** [comment]
Yep, I will create a new release once we have gone through the review process.
