### ISSUE TITLE
JOSS: Link source of the paper in the readme

### ISSUE THREAD

**Issue by destogl** [klevis-a/kinematics-vis#16]
- please add link to the `joss/paper.md` into README.md because of additional explanation
- or add place-holder for the paper link after publication into README.md

I propose to add those before "Checkout the live demo..."

**Comment by klevis-a** [comment]
This was done in commit https://github.com/klevis-a/kinematics-vis/commit/c6bf1808389999c45b57e4488592db028dbe1d8f.
