### ISSUE TITLE
JOSS: Functionality documentation

### ISSUE THREAD

**Issue by destogl** [klevis-a/kinematics-vis#17]
Please add a short documentation of functionalities in the GUI. E.g. an image with numerated buttons/visualizations explaining their functionalities and options.

**Comment by klevis-a** [comment]
@destogl this already exists, unless I am misunderstanding what you are asking for. Look at the README, it points you to where the Help button is in the GUI. The Help button is a question mark to the right of the sliding bar at the top of the GUI.
