### ISSUE TITLE
JOSS: Manual tests

### ISSUE THREAD

**Issue by destogl** [klevis-a/kinematics-vis#18]
Please consider a brief description how to test if software is working properly. Proposal:

- start software
- load specific set of example data
- screenshot what should be seen
- Using button "X" - this should happen (maybe for multiple buttons)

This can also help to understand the functionality of the software.

**Comment by klevis-a** [comment]
A basic set of manual test cases was added previously per #12. See MANUAL_TESTING.md.

**Comment by destogl** [comment]
Thanks for adding this. I propose to also link this file in the main README.md. (This is a nitpick.) Therefore, I am closing this, and you may add it if you like it.

**Comment by klevis-a** [comment]
@destogl, good point - I just added the link.
