### ISSUE TITLE
JOSS: Add references to mentioned software packages

### ISSUE THREAD

**Issue by destogl** [klevis-a/kinematics-vis#19]
- please consider adding mentioned software packages into reference section. You added links to those, but if this is working depends on PDF viewer. Therefore, please list the URL references with access dates.
- a reference to a book (and probably also Wiki-article for fast access) about Euler/Cardan references would be useful

**Comment by klevis-a** [comment]
Added references in https://github.com/klevis-a/kinematics-vis/commit/bbf0560985fe4a15d599100b743741d5293b6728. Also generated a new version of the paper.

**Comment by destogl** [comment]
It looks great, thanks!
