### ISSUE TITLE
JOSS: Usage instructions

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#2]
- The README currently only contains installation instructions
- The README (and potentially the paper) should also include a `Usage` section that guides the user into how to use the software, especially considering that:
  - "Human motion analysis is a complex topic. Biomechanists, clinicians, and trainees typically accept the results of research papers without having a consistent way to validate these results"
  - "It has previously been shown that incorrect usage of Euler/Cardan sequences can significantly misrepresent human motion"
  - "biomechanics researchers and clinicians with a limited mathematical background"
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
I had included usage instructions in the UI. See https://shouldervis.chpc.utah.edu/kinevis/main.html as an example. I can also include them in the README if you think it is necessary. Please let me know.

**Comment by engnadeau** [comment]
ah, i completely missed the `?` at the top

![image](https://user-images.githubusercontent.com/6395915/128056548-8082049e-4a09-48e2-b9dd-2bbd46c0923e.png)

yeah, it'd be great if the README at least directed the user where to look

**Comment by klevis-a** [comment]
Yep, exactly. It's not immediately obvious - I was trying to conserve screen real estate. Sure, I can add that to the README.

**Comment by klevis-a** [comment]
Added a couple of sentences directing users where to find usage instructions in https://github.com/klevis-a/kinematics-vis/commit/14b6b210d3c0292f3b27e713cd33c54ae400344c.

**Comment by engnadeau** [comment]
could you also provide a screenshot similar to mine in the README to visually show people where the help menu is

**Comment by klevis-a** [comment]
Added screenshot to README in https://github.com/klevis-a/kinematics-vis/commit/f296fc1fcba70285e3a03fe3a9d37874e364b644.
