### ISSUE TITLE
JOSS: Explain motion datasets

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#3]
- Given #2 and that this repo "provides a means for researchers to make their motion capture datasets visually explorable"
- What datasets? What requirements or limitations?
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
Dataset format is now explained in INPUT_FILES.md, see https://github.com/klevis-a/kinematics-vis/commit/ae4a033f2f08b2e4e6df986bb4d18add7746cffc.
