### ISSUE TITLE
JOSS: Add `Contributing` section to README

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#5]
- [Standard README sections](https://guides.github.com/features/wikis/#Formatting-a-readme)
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
This is now complete: https://github.com/klevis-a/kinematics-vis/commit/2a9cde872fabe0c2dad87504ebef12483c4082f8
