### ISSUE TITLE
JOSS: Alternative software and approaches?

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#6]
- The paper only mentions that researchers have typically used 2D graphs
- Is there no other visualization software available? 
- Has there really been no work done before this repo?
- Citations will be needed to validate the point
- Pros, cons, and limitations of this repo vs other approaches should also be discussed
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
@nnadeau https://github.com/klevis-a/kinematics-vis/commit/6dc0d8a522589cb835b86a5b44789657b21eea5e should address these questions.
