### ISSUE TITLE
JOSS: Mathematics section

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#7]
- While referring the reader to relevant sources is a good approach to keeping the paper concise, the section needs to be filled with at least an overview and a discussion of why each of the sources listed are relevant
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
Addressed in https://github.com/klevis-a/kinematics-vis/commit/36b7553d6086dc6f7d01d2cc24d1452f0ecb879c.
