### ISSUE TITLE
JOSS: Add  Code of conduct 

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#9]
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
Addressed in https://github.com/klevis-a/kinematics-vis/commit/a6439613fc8712b44c05b97a2662c92804b9efba
